# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 12:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0002_auto_20170620_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='time',
            field=models.IntegerField(default=1, help_text='Time in minutes for show the image.'),
        ),
        migrations.AlterField(
            model_name='propaganda',
            name='choice',
            field=models.CharField(choices=[('video', 'Video'), ('image', 'Images')], default='video', max_length=10),
        ),
    ]
